command_prefix: "-"
maintainer: MAINTAINER_DISCORD_USER_ID
discord_token: TOKEN
nickname: Apollyon

fetching_interval: 30
error_timeout: 600

rocketchat_user: USER
rocketchat_password: PASSWD
youtube_api_key: API_KEY
mampf_email: EMAIL
mampf_password: PASSWD
phug_user: USER
phug_password: PASSWD
moodle_user: USER
moodle_password: PASSWD